// Generated by scripts/generate-game-catalog.mjs. Do not edit by hand.

import type { GameManifest } from "@pfp/sdk";
import ironYard from "../../../games/iron-yard/game.manifest.js";
import partyMix from "../../../games/party-mix/game.manifest.js";
import pong from "../../../games/pong/game.manifest.js";
import raskulls from "../../../games/raskulls/game.manifest.js";
import spaceInvaders from "../../../games/space-invaders/game.manifest.js";
import stickSmash from "../../../games/stick-smash/game.manifest.js";

export const GAME_MANIFESTS = [
  ironYard,
  partyMix,
  pong,
  raskulls,
  spaceInvaders,
  stickSmash,
] satisfies GameManifest[];
